Isops 508
Iterative-Scopes/cicd-framework pull request #2
Opened 2022-08-05 19:47 UTC by is-ckothapally

2022-08-05 19:49 UTC, is-srudra approved these changes, later dismissed

2022-08-05 19:57 UTC, is-ttang requested changes
need to assume 
1) container has been built because container build may need args
2) caller has pull down code and run other testing, build container, just need to publish - tag and push

2022-08-10 13:39 UTC, is-ckothapally commented
> need to assume
> 
> 1. container has been built because container build may need args
> 2. caller has pull down code and run other testing, build container, just need to publish - tag and push

2022-08-10 13:41 UTC, is-ckothapally commented
@is-ttang the actions have been changed without build arg dependency and can be called from caller repo.

2022-08-10 16:12 UTC, is-ttang approved these changes

2022-08-10 16:12 UTC, is-ttang commented on actions/aws-login/action.yml
> +  SECRET_ID:
could you remove SECRET_ID, which is not used. Second, to use lower case for inputs

2022-08-10 16:12 UTC, is-ttang commented on actions/ecr-push/action.yml
> +name: 'Push to ECR'
do we need this action? build-ecr-image should take care

2022-08-10 16:13 UTC, merged